<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Produkty24_API</RootNamespace>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="data.sqlite" />
    <None Remove="data.sqlite-shm" />
    <None Remove="data.sqlite-wal" />
    <None Remove="wwwroot\data.sqlite" />
    <None Remove="wwwroot\data.sqlite-shm" />
    <None Remove="wwwroot\data.sqlite-wal" />
    <Content Remove="wwwroot\data.sqlite" />
    <Content Remove="wwwroot\data.sqlite-shm" />
    <Content Remove="wwwroot\data.sqlite-wal" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.9" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
